### PR TITLE
Feature/basic nlm parsing

### PR DESCRIPTION
**Pull request by marcrohloff**
Sorry for the long, delayed commit. This is the NLM parser. It parses an NLM document into an object tree but doesn't do any of the post processing (fetching bibliographic metadata, abstracts, licenses, etc).

### CODE REVIEW

**Comment by egh** [comment]
What do you think about sharing code between the API and the processor for the model? This might be tricky, since one is using ActiveRecord and the processor isn't, but certainly the JSON parsing/generation should probably be shared.

**Comment by marcrohloff** [comment]
I don't really see how. Unfortunately you cannot use AR without an actual table behind it (Although you could fake it I guess by using something like sqlite and never calling save). I really didn't have any intent to parse JSON only to generate it.

**Comment by marcrohloff** [comment]
Do you think I should change this to AR?

**Comment by egh** [comment]
No, not necessarily. I guess when I extract JSON processing that will cover 90%. As long as the 2 models support the same interface we can share that code.

**Comment by marcrohloff** [comment]
Is that something you plan on doing soon? I was going to make something
basic next so that I can do better testing.

**Comment by egh** [comment]
It’s my plan to get to that as soon as I’ve we’ve got a write API up &
running. I don’t want to keep you from doing anything though.

At Tue, 14 Oct 2014 11:20:48 -0700,
Marc Rohloff wrote:

> Is that something you plan on doing soon? I was going to make something
> basic next so that I can do better testing.
> 
> On Tue, Oct 14, 2014 at 12:15 PM, Erik Hetzner notifications@github.com
> wrote:
> 
> > No, not necessarily. I guess when I extract JSON processing that will
> > cover 90%. As long as the 2 models support the same interface we can share
> > that code.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ploslabs/rich_citations_processor/pull/1#issuecomment-59090957
> > .
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ploslabs/rich_citations_processor/pull/1#issuecomment-59091841

## 

Sent from my free software system http://fsf.org/.

**Pull request merged**
