### PR TITLE
Feature/resolve citations

### PR DESCRIPTION
**Pull request by marcrohloff**
Sorry kind of a long winded commit.
This changes URIs to be actual objects and starts off on resolving references (or possibly other info) to URIs
I also did some work to allow documents to be parsed and serialized based on mime types

### CODE REVIEW

**Comment by egh** [comment]
Thanks, Marc! I'll look at this Monday.

**Comment by egh** [comment]
Do you think we should move the serializer code here and include it in the API? I notice you have similar but slightly different serializer classes.

**Comment by marcrohloff** [comment]
I would like to but I'm not entirely sure how.

**Comment by egh** [comment]
I can try pulling them in the API code using the processor as a gem.

**Comment by marcrohloff** [comment]
Being able to use it as a gem was the intent but the models are slightly
different.

**Comment by egh** [comment]
Anyhow, I have comments but I think we can move them elsewhere.

**Pull request merged**
